import { SignedIn } from '@clerk/clerk-react'
import Head from 'next/head'
import Redirect from './redirect'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>Ryan's Todo App</h1>
      <SignedIn>
      <Redirect
        url='/todos'
      />
      </SignedIn>
    </>
  )
}
